language: java
jdk: openjdk8
deploy:
  provider: herokumv
  api_key:
    secure: WA4XBuEpHqN9NGFiljjSnQPHT0t48Q2Vvuy+wimoV/AEp/qbAawq/RQjZyegu3tSz9Sd/2wm0VagU5n4s19+EdEe0Xi+2lNAQq06sb0gCaNsCNVq2BrwOJGHFAwKVO3lT9BcPW737T2TV6xnkzyC8cAqbhvSSCH1Ob3jlsjFJcQiA/P5cultHW6qCS4R3WCnyIOifWR7syvRp6N80nnTnXBWM1ae2vpSwWsRMyBi5ayqb+1RS03Knv3xVEr3SksikGEJ2w2XnVqrNd00HUF9GDEFSQ8BDMVHC9+Si/DtOefYkm9kQQ6440xIdpstaBXV4DV/cHq+iMoc8fSeEk0tbsOF7tkCYJVQX14JzFmgjWZ5g9hH5rGyvF3PFRdFRK4v4f7S+urnnJh+dJ5YVF7wkji9sczRfQjO+NEAAnlAcMvqwqbCb4IHdKIbWE5bqMA+K9xAe2HDWfgM2WrZm7NObB5iQZPh5PhPz/2G6iIdDzZoIK9wLGAzOqxPTCQwuQozgu0OCxFNePwtigQcH1CXhonikjZFUEosKlvvw+JEIckqmRP+H6ZbvapqrT/ICy85wirH/73tzKHTCLCXDwQI8sUkveCIl7Cfekrk6FXPQzJSzVhpdA3BQ2h+yiu5NjSiHqSavJsJC7LgpNXrOVn6j/5QPh89cTRfOXrG5K+66+U=
